### ISSUE TITLE
Build Error : Fonts missing 

### ISSUE THREAD

**Issue by ksauraj** [PitchBlackRecoveryProject/manifest_pb#19]
Some fonts are missing on branch `android-12.1`.
Like `NotoSansEthiopic-Regular` & `NotoSansArmenian-Regular` and others from `NotoSans` family.
```
Exception in thread "main" java.io.IOException: Can not find the font file NotoSansBengaliUI-Regular for language as
        at com.android.recovery.tools.ImageGenerator.loadFontsByLocale(ImageGenerator.java:399)
        at com.android.recovery.tools.ImageGenerator.createGraphics(ImageGenerator.java:492)
        at com.android.recovery.tools.ImageGenerator.measureTextWidth(ImageGenerator.java:500)
        at com.android.recovery.tools.ImageGenerator.generateImage(ImageGenerator.java:618)
        at com.android.recovery.tools.ImageGenerator.main(ImageGenerator.java:755)
13:43:57 ninja failed with: exit status 1
```

**Comment by hraj9258** [comment]
@noobyysauraj I didn't faced it

**Comment by jaaat4u** [comment]
anything worked out for you? found any fix?
