### ISSUE TITLE
Don't have a product spec for: 'twrp_RMX2170.mk'

### ISSUE THREAD

**Issue by BNLOS** [PitchBlackRecoveryProject/manifest_pb#21]
your device can't be found in device sources..
Traceback (most recent call last):
  File "vendor/pb/build/tools/roomservice.py", line 428, in <module>
    fetch_device(device)
  File "vendor/pb/build/tools/roomservice.py", line 396, in fetch_device
    git_data = search_github_for_device(device)
  File "vendor/pb/build/tools/roomservice.py", line 78, in search_github_for_device
    check_repo_exists(git_data)
  File "vendor/pb/build/tools/roomservice.py", line 63, in check_repo_exists
    "roomservice".format(device, android_team))
Exception: RMX2170.mk not found in PitchBlackRecoveryProject Github, exiting roomservice
/root/pbrp/build/blueprint/microfactory/microfactory.bash: line 62: /root/pbrp/prebuilts/go/linux-x86//bin/go: No such file or directory

** Don't have a product spec for: 'twrp_RMX2170.mk'
** Do you have the right repo manifest?

**Comment by zty012** [comment]
how do u solve that
