### ISSUE TITLE
Build error: font missing

### ISSUE THREAD

**Issue by crackedmodmenu** [PitchBlackRecoveryProject/manifest_pb#24]
Not found   NotoSansEthiopic-Regular

Error: Exception in thread "main" java.io.IOException: Can not find the font file NotoSansEthiopic-Regular for language am
	at com.android.recovery.tools.ImageGenerator.loadFontsByLocale(ImageGenerator.java:399)
	at com.android.recovery.tools.ImageGenerator.createGraphics(ImageGenerator.java:492)
	at com.android.recovery.tools.ImageGenerator.measureTextWidth(ImageGenerator.java:500)
	at com.android.recovery.tools.ImageGenerator.generateImage(ImageGenerator.java:618)
	at com.android.recovery.tools.ImageGenerator.main(ImageGenerator.java:755)
[ 99% 25070/25095] //system/security/keystore2:libkeystore2 rustc src/lib.rs
ninja: build stopped: subcommand failed.
19:40:59 ninja failed with: exit status 1
Error: Process completed with exit code 1.

**Comment by ShazuxD** [comment]
I too faced the same error of missing fonts in source here is the all missing fonts
- stay in source dir & run this and build
cd external/noto-fonts/other &&wget https://github.com/ShazuxD/extras/raw/main/font.zip &&unzip -o font.zip &&cd ../../..

**Comment by manu-palmero** [comment]
Did you fix it?

**Comment by crackedmodmenu** [comment]
yes

**Comment by manu-palmero** [comment]
How?

**Comment by crackedmodmenu** [comment]
stay in source dir & run this and build

cd external/noto-fonts/other &&wget https://github.com/ShazuxD/extras/raw/main/font.zip &&unzip -o font.zip &&cd ../../..

**Comment by manu-palmero** [comment]
That GitHub user does not exist :(

**Comment by cd-Crypton** [comment]
> That GitHub user does not exist :(

Try this, @manu06202579. Make sure you are in root source.

```
cd external/noto-fonts/other && wget https://github.com/cd-Crypton/custom-recovery-extras/raw/main/missing-font.zip && unzip -o missing-font.zip && cd ../../..
```
